---
title: " " #replace the title with something short and catchy to represent your project
subtitle: "John Higdon's Data Science Portfolio"
output:
  html_document:
    df_print: paged
---

## Abstract

The topic we will be exploring is Gross Domestic Product and Personal income in the United States between Quarter 1 2017 to Quarter 1 2019. The main motive for choosing this topic was to determine if overall GDP has a significant affect on recent personal income and vice versa. Intuitively we would expect that this may be the case. This project explores if this notion is true or false.

### 1. Discovery and Data Preparation

Here we prep our data the best we can and explore what we found using visualizations.

[Portfolio: Part 1](https://violetinferno.github.io/DataSciencePortfolio/p1.html)

### 2. Model Planning and Building

In part 2 we add another data source to our data set to glean additional information. Statistical models are built for various predictive elements to determine if the model produces statistically significant results.

[Portfolio: Part 2](https://violetinferno.github.io/DataSciencePortfolio/p2.html)

### 3. Results and Operationalization

Coming soon...